### ISSUE TITLE
Falscher Text zur Abwahl

### ISSUE THREAD

**Issue by mohe2015** [untergeekDE/feldmannreferendum#1]
https://github.com/untergeekDE/feldmannreferendum/blob/a5bef5fcd9ea803fcd50762d1207bb3ce22c6d03/R/update_feldmann.R#L103

Fehlt an dieser Stelle ein "nicht"?

**Comment by mohe2015** [comment]
Sieht so aus, als wurde es eben gefixt

**Comment by mohe2015** [comment]
Oh, ist hier aber noch nicht gepusht

**Comment by untergeekDE** [comment]
Alles ein wenig heiße Nadel heute :)
